services:
  postgres:
    image: postgres:16-alpine
    container_name: upkeep-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: upkeep_db
      POSTGRES_USER: upkeep
      POSTGRES_PASSWORD: upkeep

    ports:
      - "5432:5432"

    volumes:
      - upkeep_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-d", "upkeep_db", "-U", "upkeep"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  upkeep_db_data:
